### ISSUE TITLE
Example google-translate-api-credentials.json

### ISSUE THREAD

**Issue by devsecfranklin** [goproslowyo/trumpet#5]
Can you provide and example `google-translate-api-credentials.json` , how to register for it, etc.

**Comment by goproslowyo** [comment]
yep! https://cloud.google.com/text-to-speech/docs/libraries#setting_up_authentication

and [readme](https://github.com/goproslowyo/trumpet/commit/eb876c665415b3d2c7f38b08a1b57a6ee7847abf).
